### ISSUE TITLE
How to access midea-discover for config with non-container Home Assistant OS

### ISSUE THREAD

**Issue by keithfree** [mac-zhou/midea-ac-py#169]
**Describe the bug （描述一下问题）**
I recently installed two Midea  U-Shaped Window A/C units (models MAW08V1QWT and MAW12V1QWT) in my home and am looking for help with how to use midea-ac-py. 

1. How do I identify "Midea AC Device's applianceId"?
2. How do I know if "V3 is required" for my AC units?
3. If V3 is required, how do I get **midea-discover** in order to identify the token and k1 values? 

```yaml
climate:
  - platform: midea_ac
    host: 192.168.1.100
    id: 123456789012345
    # v3 need token and k1(key)
    # token: ACEDDA53831AE5DC...(Length 128)
    # k1: CFFA10FC...(Length 64)
```

**Versions (版本信息)**
 - Raspberry Pi 4
 - Home Assistant Core 2022.6.7
 - Home Assistant Supervisor 2022.05.3
 - Home Assistant OS 8.2
 - Home Assistant Frontend version: 20220601.0 - latest
