### ISSUE TITLE
Syntax for multiple Aircon units

### ISSUE THREAD

**Issue by stevecopecs** [mac-zhou/midea-ac-py#192]
**Describe the bug （描述一下问题）**
I have two Midea units which I want to operate from within HA
Individually they work correctly with a flat (non sub-nested) yaml configuration, exactly as you have in your instructions
I cannot figure out the yaml syntax for multiple units

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
If applicable, add screenshots or your home-assistant log file or pcap file to help explain your problem.
请提交相关截图，日志，抓包让开发者能够更快的解决问题

**Versions (版本信息)**
 - Home Assistant version: latest
 - Midea msmart version: latest

**Comment by stevecopecs** [comment]
Hi all, I'm still battling with this.
Anyone able to help with the syntax for multiple units please ?

**Comment by mill1000** [comment]
Pretty sure it's something like
```yaml
climate:
  - platform: midea_ac
    host: <unit1 ip address>
    id: <unit1 ID>
  - platform: midea_ac
    host: <unit2 ip address>
    id: <unit2 ID>
```
