### ISSUE TITLE
error when adding multiple midea AC

### ISSUE THREAD

**Issue by Karolusin** [mac-zhou/midea-ac-py#199]
**Describe the bug （描述一下问题）**
When i am adding more than one AC only the last one is working, rest are no longer avanible. 

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
If applicable, add screenshots or your home-assistant log file or pcap file to help explain your problem.
请提交相关截图，日志，抓包让开发者能够更快的解决问题
![image](https://user-images.githubusercontent.com/25100218/196931577-f77817af-960a-4ff6-b00a-ad1e89ecfc69.png)
![image](https://user-images.githubusercontent.com/25100218/196931763-605a70f0-3a8c-4090-b587-014532c1feeb.png)

**Versions (版本信息)**
 - Home Assistant version: 2022.10.4
 - Midea msmart version: v0.2.3

**Comment by paradox37** [comment]
This is not a bug. Your configuration is wrong. This is how it should be:

```
climate:
  - platform: midea_ac
    host: 192.168.1.100
    id: 123456789012345
  - platform: midea_ac
    host: 192.168.1.100
    id: 123456789012345
```
