### ISSUE TITLE
outdoor_temperature. Is it possible to show the property/attribute outdoor_temperature ?

### ISSUE THREAD

**Issue by rafaelmlcb** [mac-zhou/midea-ac-py#46]
Is it possible to show the property/attribute outdoor_temperature in Home Assistant ?

**Comment by sklein972** [comment]
+1

**Comment by smith113311** [comment]
Try creating this sensor in config.yaml (polling every 5 hours):

sensor:
  - platform: template
    sensors:
      outdoor_temperature:
        friendly_name: "Outdoor Temperature"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('climate.inventor_ac_00000000000d', 'outdoor_temperature' )}}"
        icon_template: mdi:thermometer

**Comment by ianschmitz** [comment]
FWIW i followed the instructions here https://www.home-assistant.io/integrations/template/ along with the suggestion from @smith113311 and came up with:

```yaml
template:
  - sensor:
    - unique_id: "heat_pump_north_outdoor_temp"
      name: "Outdoor Temperature North"
      unit_of_measurement: "°C"
      state: "{{ state_attr('climate.midea_ac_30786325801344', 'outdoor_temperature' )}}"
      icon: mdi:thermometer
```

where `climate.midea_ac_xxx` is the id of the indoor unit as shown in the Developer Tools -> States page in HASS.
