### ISSUE TITLE
温度步长不能正常设置

### ISSUE THREAD

**Issue by pydog** [mac-zhou/midea-ac-py#6]
temp_step 为非1的情况设置不能生效

1. 在configuration.yaml 中添加tem_step:
temp_step: 0.5

2. 通过UI 设置温度
3. 设置后过一会系统返回整数位的值并刷新UI位整数位，比如设置的是28.5度，最后刷新后为28，设置的是29.5度返回的就是29

**Expected behavior**
可以正确安装步长设置，当然前天是空调是支持的

**Versions**
 - Home Assistant version: 109.6
 - Midea integration version (commit hash): 
commit 99ba820175b1a395d5f5c3a2120f673b3e22363b
Author: mac_zhou <mac.zfl@gmail.com>
Date:   Fri May 8 16:01:06 2020 +0800

**Comment by mac-zhou** [comment]
嗯 虽然插件中给配置 但协议解析中还是仅仅解析整数
需要提交一些log和抓包过来给我看一下

**Comment by mac-zhou** [comment]
请升级最新版本，或者直接修改manifest.json中```msmart==0.1.13```
ha的配置中增加:
```
logger:
  default: info
  logs:
    custom_components.midea: debug
    msmart: debug
```
再有相关问题 请筛选出相关log反馈过来
