### ISSUE TITLE
Support for non AC Midea devices (such as Midea EVA II Pro Wifi dehumidifier)

### ISSUE THREAD

**Issue by 35gh** [mac-zhou/midea-ac-py#98]
**Describe the solution you'd like （描述需求）**

Would it be possible to add support for other non AC devices, such as Midea EVA II Pro Wifi dehumidifier?
Those devices can be controlled with the same app.

**Comment by SebastianStorb** [comment]
You solved this bug:
`INFO:msmart.cli:*** Found a device: {'type': 'ac', 'support': True, 'version': 3, 'ip': '192.168.1.51', 'id': 23XXXXXXXXXXXX, 'port': 6444, 'token': '8AA0A1181BAC26461843B96780BDD1D1375DFD6D3A151199B8FA46CF076078B7EEAAEAAE3181DDBDF7E034A779061FD686DEFB1E90E0DAE6DCDFBF3AAEFCAE28', 'key': '49DBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'ssid': 'net_ac_XXXX'}
INFO:msmart.cli:*** Found a device: {'type': 'ac', 'support': True, 'version': 3, 'ip': '192.168.1.41', 'id': 18XXXXXXXXXXXX, 'port': 6444, 'token': '4E4416432AB917D4B7604AC9D053F95E85374FEB827D4E137D506A1E7596C6CF576E0FEF16C9069A775F5868B3C6C661FDDC184143DD42916F4F89A5D9D6B895', 'key': '1524XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'ssid': 'net_ac_XXXX'}
sebastian@debian-server:~$`

but the ACs are still not working:

Is something wrong in my configuration.yaml?

```
# Midea_AC
climate:
  - platform: midea_ac
    host: 192.168.1.41
    id: 18XXXXXXXXXXXX
    token: 4E4416432AB917D4B7604AC9D053F95E85374FEB827D4E137D506A1E7596C6CF576E0FEF16C9069A775F5868B3C6C661FDDC184143DD42916F4F89A5D9D6B895
    port: 6444

#climate:
  - platform: midea_ac
    host: 192.168.1.51
    id: 23XXXXXXXXXXXX
    token: 
8AA0A1181BAC26461843B96780BDD1D1375DFD6D3A151199B8FA46CF076078B7EEAAEAAE3181DDBDF7E034A779061FD686DEFB1E90E0DAE6DCDFBF3AAEFCAE28
```
